language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
    - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
    
sudo: required
    
licenses:
  - '.+'
  
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20
 
jdk:
  - oraclejdk8

script:
  - ./gradlew assembleDebug
